"""Add stock_status column to product table

Revision ID: 1718b8c225ca
Revises: 3c5cf118d35c
Create Date: 2023-09-10 21:43:32.869088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1718b8c225ca'
down_revision: Union[str, None] = '3c5cf118d35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_status')
    # ### end Alembic commands ###
