"""add loyalty pointe to customer repr

Revision ID: ad4f4d498aa8
Revises: 04a1ca62d063
Create Date: 2023-09-07 17:18:35.040056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4f4d498aa8'
down_revision: Union[str, None] = '04a1ca62d063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
