"""remove loyalty points from customer fullname

Revision ID: cc258bfd6872
Revises: ad4f4d498aa8
Create Date: 2023-09-07 17:22:37.112294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc258bfd6872'
down_revision: Union[str, None] = 'ad4f4d498aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
