"""added total_amount column to purchase table

Revision ID: cc69d3561c69
Revises: 34c6251c8bf3
Create Date: 2023-09-07 23:42:11.483805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc69d3561c69'
down_revision: Union[str, None] = '34c6251c8bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('total_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'total_amount')
    # ### end Alembic commands ###
