"""add column to table purchases

Revision ID: e511a6df438d
Revises: 79e8268d4cc3
Create Date: 2023-09-06 15:33:33.023743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e511a6df438d'
down_revision: Union[str, None] = '79e8268d4cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'quantity')
    # ### end Alembic commands ###
